name: Test

on: [push]

jobs:
  test:
   runs-on: ubuntu-22.04

   steps:
    - uses: actions/checkout@v2
      
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
       python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2